title = "Ken Finnigan"
baseURL = "https://kenfinnigan.me"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-136937470-1"
enableRobotsTXT = true

disqusShortname = "kenfinnigan"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/kenfinnigan"
  github = "https://github.com/kenfinnigan"
  linkedin = "https://linkedin.com/in/kenfinnigan"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/kings-cross.jpg"
  custom_css = ["css/custom.css"]
  recent_posts_number = 3
  show_reading_time = true

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
