= The Feedback Chasm

:page-date: 2024-09-24
:page-summary: There's a _Feedback Chasm_ between our current role and any future one...

There's a _Feedback Chasm_ between our current role and any future one.

We receive a variety of feedback from many people throughout our careers.
Feedback from our current role
is from an environment we're familiar and, hopefully, comfortable in.

In this post I talk about the _Feedback Chasm_ and why it's a problem.

== Current Role Feedback

Any role we're in, we receive feedback from many people.
From managers, mentors, peers, and direct reports, to name a few.
Hopefully feedback is given freely and openly.
And more frequently than yearly performance reviews.
With any feedback we receive,
we are free to choose whether to act on that feedback, or not.

The feedback we receive is often targeted at our current role.
How we're doing as a leader, manager, engineer, or whatever role we're in.
What we need to do for promotions, raises,
or other future roles in the same company.
We may also receive feedback which is generally applicable to any role,
but less frequently.

== Future Role Feedback

When interviewing for a new role at a new company,
we don't consider the importance of feedback.
We're focused on the interview itself,
and whether we're a good fit for the team and company.
We rely on our existing skills and experience from current and previous roles,
hoping they're enough.

What happens when our current skills are not enough?
We don't get an offer,
and we're often left wondering why.

Sometimes we do get feedback,
but it can be vague and not actionable.
We're left to our own devices to figure out what to do next.
Are we lacking in certain skills?
Do I need more technical or soft skills?

This is the _Feedback Chasm_.

== The Feedback Chasm

The feedback we receive for our current role,
is often not the same feedback we need to land a future role.
Feedback from interviewing for a new role is key to bridging the gap.
Without this feedback,
we're destined to never reach the next step in our careers.

Why do we not receive feedback when interviewing?
There can be many reasons as to why.
Sometimes it's a lack of time to distill the internal comments into shareable feedback.
Other times companies do not want to give specific feedback,
for fear of revealing too much information about their internal processes.
It could also be a fear of lawsuits,
or simply a lack of understanding of the importance of feedback for a candidate.

Without receiving feedback from the interviewing process,
we won't know how to improve.

As candidates,
interviewing requires a significant time investment.
We spend several hours in interviews, and more outside of them.
Preparing for interviews,
writing interview notes,
researching a company, and more.
It's not unreasonable to expect a small amount of feedback for the time invested.
Surely a few pieces of feedback could be provided in less than half an hour.

== Jumping the Feedback Chasm

How can we reach the other side of the _Feedback Chasm_?

One approach is ensuring we have mentors outside our current company.
They could be former colleagues, or people you've met throughout your career.
Attending conferences, online groups, or local user groups, there are many places to find a mentor.
Even if they have not worked at the company you want to join,
their feedback can be invaluable.
What you want is for their feedback to differ from what you receive at any current role.
The differing perspectives and opinions are key to growing beyond your current company and role.

What else can we do?

Some companies will offer to connect you with employees directly to hear about the culture and work environment.
This typically occurs once you've had an interview or two already,
so will not be of help in the early stages of the interview process.

However, the largest benefit comes from the industry placing a higher importance on providing feedback to candidates.
Without this feedback,
we're destined to continue making it difficult for everyone to land their dream job.
Granted,
not all feedback we receive may be useful,
or which we want to act on.

But it's a better place than not knowing anything.

== Conclusion

The _Feedback Chasm_ is a problem for the industry.
We're increasing the likelihood of limiting people's potential for growth.
Feedback is the engine driving our growth.
What that engine propelling us,
or being limited to small sets of feedback,
we may not reach where we want to go.

We need to ensure we're getting feedback from many different avenues,
both internally and externally.

However, the largest pieces of potentially career changing feedback we receive,
needs to come from the interview process itself.
The industry must change it's approach to providing feedback,
and give it freely.
Candidates invest a large amount of time in the process with no guarantees.
The company should want to provide feedback to help them improve,
increasing the chance of them being a future employee.
