---
title: "Introduction"
date: 2019-02-08T20:54:25-05:00
show_reading_time: false
draft: true
---

It's definitely weird to think that this is the first time I will have had a personal blog in the over 20
years that I've been working with technology of various kinds.

<!--more-->

Maybe not so weird when I think that it's probably been on my **todo list** for nearly 10 of those years.
Possibly longer.
It's actually been on my list so long I can't be sure how long it's been there!

So I finally pulled out the proverbial finger and put together a blog.

== A bit about me

I've been working on open source projects for about 10 years or so now,
and I've enjoyed every minute of being part of something in each of the communities that I've participated in.

What's more, being able to contribute to open source projects while working for Red Hat has been fantastic.
It makes the job even more rewarding being able to participate openly with communities of different projects.

I've always enjoyed playing with computers,
and in particular programming on them.
The first computer my family had in the early 80's was a Commodore 64.
At the time it seemed like the games were so amazing!
A couple of years after that we upgraded to the Commodore 128D,
which is when I really began learning to program.

The first computer that was mine alone,
I bought a second hand XT from Gateway with my pocket money.
It was 1987 and it had a whopping 20MB HDD and 1280Kb RAM,
and of course the wonderful 5 1/4" floppy drive!
My dad would bring home old versions of software they'd been using at his work for me to play around with.
I spent many hours installing dBase IV, Lotus 1-2-3, and the like.
Continually switching through up to a dozen floppy disks to complete an installation.
Those were the days!

== What will this blog be about?

Honestly, I'm not entirely sure it will have a defined theme or group of topics right now.
It will very much depend on how my interests change and what I might be working on at a specific time.

What I can say is that there's definitely going to be topics on computing,
most likely focusing around software development, microservices, and cloud.
I may also talk about interesting genealogical things I find in doing my research.
Some of which could cross over into software related to genealogy as well.

Lastly, you may find the odd post about family life or vacations we have taken.

== Last words

A lot of the above is a round about way of saying,
_this blog won't be for everyone_.

At any rate,
I hope from time to time you find interesting topics I've discussed here.
And if you do, please let me know.
I may decide to talk deeper about those topics that others also find of interest.

Thanks for reading, Ken.
