== Holy Grail
:page-title: Holy Grail
:page-description: Searching for a job

As The Crusader enters a foreign land,
 +
Checking his trusty sword,
 +
In the hope that it will assist
 +
With the search for his Holy Grail.

Seeking out the Seers of the land,
 +
Is a daunting and challenging prospect.
 +
At times they will race to assist in a quest.
 +
Yet at others, they seem to be non-existent.

Speaking with the Seers requires great concentration
 +
To ensure all the hidden meanings about a path
 +
Are understood and adhered to.  Not doing so,
 +
Can have dire consequences for The Crusader's existence.

While on the path divined by a Seer.
 +
It can be a long and winding road,
 +
With many highs and lows along the way.
 +
Often, the path appears to have no end.

There are many Seers on the road to glory.
 +
Some will submit to the might of the sword.
 +
While others will just pass by on the road,
 +
As they have divined that their path “Can not be travelled by thee!”

There will be many times on arriving
 +
At the destination given by a Seer,
 +
That the treasure is no longer present.
 +
Or was never there at all.  Most disheartening!

After months of searching along many roads,
 +
Being told to turn back by some on the path.
 +
The Crusader begins to question the might of his sword,
 +
And how he can begin to improve its' strength.

When despair reaches so far and wide,
 +
That a way out appears to be impossible.
 +
A Seer crosses The Crusader's path.  Somehow,
 +
He seems more knowledgeable than all the others.

This Seer knows what is sought,
 +
Without a word having been uttered.
 +
Enlightened on the ways of the true path.
 +
The Crusader is guided on the road to glory.

After a passage of time,
 +
A mountain in the distance begins to grow.
 +
The Crusader is lead to an entrance,
 +
Where The Seer bade him to enter alone.

The Crusader grabbed the hilt of his sword,
 +
For reassurance, before slowly entering.
 +
Stumbling in the dark, trying to find his way,
 +
Until reaching a dimly lit cavern.

He saw a man of simple means, probably a Scribe,
 +
Standing in the cavern holding his Holy Grail!
 +
The Crusader rushed The Scribe, wielding his sword,
 +
Preparing to strike him down and accomplish his quest.

At the last moment The Crusader stopped.
 +
The Scribe was grinning from ear to ear.
 +
Returning his sword to its' scabbard,
 +
He asked The Scribe why he was not afraid.

The Scribe replied, “It was not my time”.
 +
Asked if this was a test, The Scribe just grinned.
 +
They spoke about trivial matters, before The Crusader
 +
Asked for his Holy Grail, and The Scribe gave it him.

Surprised by this, The Crusader asked why it was given.
 +
“You needed to prove your worth with a means
 +
other than your sword.  And you did”, replied The Scribe.
 +
The Crusader was now deemed fit to join The Scribe's Master in battle!

The next day was the first of many where The Crusader
 +
Used his sword to remove many obstacles,
 +
Complete tasks assigned by his new Master,
 +
And assist fellow crusaders in theirs.

The Crusader attacked his new challenge with great vigour,
 +
Seeking further inspiration and contentment.
