name: Gatsby Publish

on:
  push:
    branches: [ develop ]

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '20.x' ]

    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        working-directory: main
      - run: npm run build
        working-directory: main
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: site
      - run: cp -r * ../../site
        working-directory: main/public
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Publish updated site"
        working-directory: site
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          directory: site
